import { AppData } from '../types';
import { safeCalculate } from './validators';

// Export data to JSON
export const exportDataAsJSON = (data: AppData, filename: string = 'life-os-backup.json') => {
  try {
    const dataStr = JSON.stringify(data, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    return { success: true, message: 'Data exported successfully' };
  } catch (error) {
    console.error('Export error:', error);
    return { success: false, message: 'Failed to export data' };
  }
};

// Export data to CSV
export const exportDataAsCSV = (data: AppData, filename: string = 'life-os-transactions.csv') => {
  try {
    const headers = ['Date', 'Description', 'Amount', 'Category', 'Type'];
    const rows = data.transactions.map(t => [
      new Date(t.date).toLocaleDateString(),
      t.description,
      t.amount,
      t.category,
      t.type
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    const dataBlob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    return { success: true, message: 'CSV exported successfully' };
  } catch (error) {
    console.error('CSV export error:', error);
    return { success: false, message: 'Failed to export CSV' };
  }
};

// Import data from JSON
export const importDataFromJSON = (file: File): Promise<AppData | null> => {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const imported = JSON.parse(e.target?.result as string);
        resolve(imported as AppData);
      } catch (error) {
        console.error('Import error:', error);
        resolve(null);
      }
    };
    reader.readAsText(file);
  });
};

// Generate financial summary report
export const generateFinancialSummary = (data: AppData): string => {
  const totalIncome = safeCalculate(() =>
    data.transactions
      .filter(t => t.type === 'INCOME')
      .reduce((sum, t) => sum + t.amount, 0), 0
  );

  const totalExpenses = safeCalculate(() =>
    data.transactions
      .filter(t => t.type === 'EXPENSE')
      .reduce((sum, t) => sum + t.amount, 0), 0
  );

  const totalAssets = safeCalculate(() =>
    data.assets.reduce((sum, a) => sum + a.value, 0), 0
  );

  const totalLiabilities = safeCalculate(() =>
    data.liabilities.reduce((sum, l) => sum + (l.totalAmount - l.paidAmount), 0), 0
  );

  const netWorth = totalAssets - totalLiabilities;

  return `
=== LIFE OS FINANCIAL SUMMARY ===
Generated: ${new Date().toLocaleString()}

INCOME & EXPENSES
Total Income: $${totalIncome.toLocaleString()}
Total Expenses: $${totalExpenses.toLocaleString()}
Net Savings: $${(totalIncome - totalExpenses).toLocaleString()}

ASSETS & LIABILITIES
Total Assets: $${totalAssets.toLocaleString()}
Total Liabilities: $${totalLiabilities.toLocaleString()}
Net Worth: $${netWorth.toLocaleString()}

TASKS & HABITS
Pending Tasks: ${data.tasks.filter(t => !t.completed).length}
Active Habits: ${data.habits.length}
Wishlist Items: ${data.wishlist.length}

INVESTMENTS
Total Investments: ${data.investments.length}
Insurance Policies: ${data.insurancePolicies.length}

Generated by Life OS on ${new Date().toDateString()}
  `.trim();
};
